######################################################################
# Automatically generated by qmake (3.0) Wed Apr 1 11:54:12 2015
######################################################################

TEMPLATE = app
TARGET = customheader
INCLUDEPATH += .

QT += widgets

SOURCES += main.cpp \
           customtableheader.cpp

HEADERS += customtableheader.h

FORMS += \
    importdialog.ui
